const JOBS_DATA = [
    {
        id: 1,
        title: "SDE Intern",
        company: "Swiggy",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        salaryRange: "₹25k–₹40k/month Internship",
        skills: ["Java", "Spring Boot", "REST APIs"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        applyUrl: "https://careers.swiggy.com",
        description: "Join our backend team to build scalable services. \nYou will work on high-throughput systems processing millions of orders. \nideal for final year students or fresh graduates with strong DSA skills."
    },
    {
        id: 2,
        title: "Frontend Developer",
        company: "CRED",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        salaryRange: "12–18 LPA",
        skills: ["React", "Redux", "TypeScript", "Tailwind"],
        source: "Naukri",
        postedDaysAgo: 0,
        applyUrl: "https://careers.cred.club",
        description: "Start working on the most beautiful app in India. \nWe are looking for frontend wizards who obsess over pixel perfection. \nProficiency in complex animations and React performance optimization is a must."
    },
    {
        id: 3,
        title: "Systems Engineer Trainee",
        company: "Infosys",
        location: "Mysore",
        mode: "Onsite",
        experience: "Fresher",
        salaryRange: "3.6–5 LPA",
        skills: ["Python", "SQL", "Basics of OOPs"],
        source: "Naukri",
        postedDaysAgo: 5,
        applyUrl: "https://www.infosys.com/careers",
        description: "Excellent opportunity for fresh graduates to start their career. \nIncludes a comprehensive 6-month training program at our world-class Mysore campus. \nWork on enterprise-scale projects for global clients."
    },
    {
        id: 4,
        title: "Backend Engineer",
        company: "Razorpay",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3",
        salaryRange: "14–22 LPA",
        skills: ["Go", "Microservices", "PostgreSQL"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        applyUrl: "https://razorpay.com/jobs",
        description: "Scale India's payments infrastructure. \nLooking for engineers who love distributed systems and concurrency. \nRemote-first culture with occasional meetups."
    },
    {
        id: 5,
        title: "Data Analyst",
        company: "Flipkart",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "0-1",
        salaryRange: "6–10 LPA",
        skills: ["SQL", "Excel", "Tableau", "Python"],
        source: "Indeed",
        postedDaysAgo: 3,
        applyUrl: "https://www.flipkartstages.com",
        description: "Analyze shopping trends for millions of users. \nResponsibilities include creating dashboards and ad-hoc reporting. \nStrong statistical foundation required."
    },
    {
        id: 6,
        title: "Java Developer",
        company: "TCS",
        location: "Pune",
        mode: "Onsite",
        experience: "3-5",
        salaryRange: "7–12 LPA",
        skills: ["Java 17", "Spring Cloud", "Hibernate"],
        source: "Naukri",
        postedDaysAgo: 7,
        applyUrl: "https://www.tcs.com/careers",
        description: "Leading digital transformation for a banking client. \nMust have experience in building secure and scalable APIs. \nKnowledge of cloud platforms like AWS is a plus."
    },
    {
        id: 7,
        title: "React Native Developer",
        company: "Zomato",
        location: "Gurgaon",
        mode: "Office",
        experience: "1-3",
        salaryRange: "10–16 LPA",
        skills: ["React Native", "Redux", "Mobile UI"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        applyUrl: "https://www.zomato.com/careers",
        description: "Build the app that feeds India. \nWork on improving app performance and user experience. \nFast-paced environment with high ownership."
    },
    {
        id: 8,
        title: "Cloud Support Associate",
        company: "Amazon",
        location: "Hyderabad",
        mode: "Hybrid",
        experience: "0-1",
        salaryRange: "5–8 LPA",
        skills: ["Linux", "Networking", "AWS Basics"],
        source: "Naukri",
        postedDaysAgo: 4,
        applyUrl: "https://www.amazon.jobs",
        description: "Kickstart your cloud career with AWS. \nTroubleshoot complex technical issues for global customers. \nRotational shifts with generous allowance."
    },
    {
        id: 9,
        title: "Product Designer",
        company: "Zoho",
        location: "Chennai",
        mode: "Onsite",
        experience: "1-3",
        salaryRange: "8–14 LPA",
        skills: ["Figma", "UI/UX", "Prototyping"],
        source: "Zoho Careers",
        postedDaysAgo: 9,
        applyUrl: "https://www.zoho.com/careers",
        description: "Design tools used by millions of businesses. \nFocus on simplicity and minimalist design principles. \nCollaborate closely with product managers and developers."
    },
    {
        id: 10,
        title: "Graduate Engineer Trainee",
        company: "Wipro",
        location: "Hyderabad",
        mode: "Onsite",
        experience: "Fresher",
        salaryRange: "3.5–4.5 LPA",
        skills: ["C++", "Java", "Communication"],
        source: "Naukri",
        postedDaysAgo: 6,
        applyUrl: "https://careers.wipro.com",
        description: "Part of the Elite National Talent Hunt. \nWork on diverse projects across various domains. \nStructured training path provided."
    },
    {
        id: 11,
        title: "DevOps Engineer",
        company: "PhonePe",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "3-5",
        salaryRange: "18–28 LPA",
        skills: ["Kubernetes", "Docker", "Jenkins", "Ansible"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        applyUrl: "https://www.phonepe.com/careers",
        description: "Manage infrastructure for millions of transactions per day. \nAutomate deployment pipelines and ensure high availability. \nStrong Linux background required."
    },
    {
        id: 12,
        title: "Associate Software Engineer",
        company: "Accenture",
        location: "Mumbai",
        mode: "Hybrid",
        experience: "0-1",
        salaryRange: "4.5–6.5 LPA",
        skills: ["SAP", "ABAP", "Java"],
        source: "Naukri",
        postedDaysAgo: 8,
        applyUrl: "https://www.accenture.com/in-en/careers",
        description: "Implement enterprise solutions for Fortune 500 clients. \nWork in a collaborative global team environment. \nLearning opportunities in latest tech stacks."
    },
    {
        id: 13,
        title: "QA Engineer (Manual)",
        company: "Paytm",
        location: "Noida",
        mode: "Onsite",
        experience: "1-3",
        salaryRange: "5–9 LPA",
        skills: ["Manual Testing", "JIRA", "SQL"],
        source: "Indeed",
        postedDaysAgo: 3,
        applyUrl: "https://paytm.com/careers",
        description: "Ensure the quality of payments and commerce flows. \nWrite test cases and execute regression suites. \nMove towards automation with guidance."
    },
    {
        id: 14,
        title: "Software Engineer",
        company: "Microsoft",
        location: "Hyderabad",
        mode: "Hybrid",
        experience: "Fresher",
        salaryRange: "14–18 LPA",
        skills: ["C#", ".NET", "Azure"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        applyUrl: "https://careers.microsoft.com",
        description: "Work on world-class products like Azure and Office 365. \nSolve complex engineering challenges at scale. \nInclusive culture with great mentorship."
    },
    {
        id: 15,
        title: "Android Developer",
        company: "Urban Company",
        location: "Gurgaon",
        mode: "Onsite",
        experience: "1-3",
        salaryRange: "12–20 LPA",
        skills: ["Kotlin", "Android SDK", "MVVM"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        applyUrl: "https://www.urbancompany.com/careers",
        description: "Build the app that powers home services in India. \nFocus on app performance and smooth UI/UX. \nWork with a talented mobile team."
    },
    {
        id: 16,
        title: "Business Analyst",
        company: "Deloitte",
        location: "Hyderabad",
        mode: "Hybrid",
        experience: "0-1",
        salaryRange: "6–9 LPA",
        skills: ["Excel", "Requirement Gathering", "Visio"],
        source: "Naukri",
        postedDaysAgo: 5,
        applyUrl: "https://www2.deloitte.com/in/en/careers",
        description: "Bridge the gap between business and technology. \nGather requirements and document processes. \nWork with clients to understand their needs."
    },
    {
        id: 17,
        title: "Frontend Intern",
        company: "Zerodha",
        location: "Bangalore",
        mode: "Remote",
        experience: "Fresher",
        salaryRange: "₹20k–₹30k/month Internship",
        skills: ["Vue.js", "JavaScript", "CSS"],
        source: "Zerodha Careers",
        postedDaysAgo: 2,
        applyUrl: "https://careers.zerodha.com",
        description: "Work on Kite, the largest trading platform in India. \nWe love clean code and minimalistic interfaces. \nHigh degree of freedom and responsibility."
    },
    {
        id: 18,
        title: "Python Developer",
        company: "Cognizant",
        location: "Chennai",
        mode: "Hybrid",
        experience: "3-5",
        salaryRange: "8–14 LPA",
        skills: ["Django", "Flask", "AWS"],
        source: "Naukri",
        postedDaysAgo: 6,
        applyUrl: "https://careers.cognizant.com",
        description: "Build backend services for healthcare clients. \nExperience with REST APIs and database design is essential. \nAgile workflow with bi-weekly sprints."
    },
    {
        id: 19,
        title: "Full Stack Engineer",
        company: "Groww",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        salaryRange: "15–25 LPA",
        skills: ["React", "Node.js", "Spring Boot"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        applyUrl: "https://groww.in/careers",
        description: "Simpilify investing for millions of Indians. \nWork across the full stack from database to UI. \nOwnership driven culture."
    },
    {
        id: 20,
        title: "Data Engineer",
        company: "Ola",
        location: "Bangalore",
        mode: "Onsite",
        experience: "3-5",
        salaryRange: "16–24 LPA",
        skills: ["Spark", "Hadoop", "Scala"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        applyUrl: "https://olacabs.com/careers",
        description: "Handle petabytes of mobility data. \nBuild data pipelines for real-time analytics. \nOptimize data storage and retrieval systems."
    },
    {
        id: 21,
        title: "Technical Support Engineer",
        company: "Dell",
        location: "Bangalore",
        mode: "Hubrid",
        experience: "0-1",
        salaryRange: "4–6 LPA",
        skills: ["Windows Server", "Networking", "Troubleshooting"],
        source: "Naukri",
        postedDaysAgo: 7,
        applyUrl: "https://jobs.dell.com",
        description: "Provide enterprise support for Dell servers and storage. \nDiagnose hardware and software issues. \n24/7 rotational shifts available."
    },
    {
        id: 22,
        title: "Software Developer",
        company: "Oracle",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        salaryRange: "12–20 LPA",
        skills: ["Java", "PL/SQL", "Cloud"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        applyUrl: "https://www.oracle.com/corporate/careers",
        description: "Join the OCI team to build cloud infrastructure. \nDeep dive into database internals and cloud orchestration. \nComplex problem solving required."
    },
    {
        id: 23,
        title: "Cyber Security Analyst",
        company: "HCL Tech",
        location: "Noida",
        mode: "Onsite",
        experience: "1-3",
        salaryRange: "6–10 LPA",
        skills: ["Network Security", "SIEM", "Python"],
        source: "Naukri",
        postedDaysAgo: 5,
        applyUrl: "https://www.hcltech.com/careers",
        description: "Monitor SOC for security threats. \nAnalyze logs and respond to incidents. \nKeep up to date with latest vulnerabilities."
    },
    {
        id: 24,
        title: "Salesforce Developer",
        company: "Capgemini",
        location: "Mumbai",
        mode: "Hybrid",
        experience: "3-5",
        salaryRange: "10–16 LPA",
        skills: ["Apex", "Visualforce", "Lightning"],
        source: "Naukri",
        postedDaysAgo: 4,
        applyUrl: "https://www.capgemini.com/careers",
        description: "Customize Salesforce solutions for global clients. \nWrite Apex triggers and classes. \nCertifications are highly preferred."
    },
    {
        id: 25,
        title: "Machine Learning Engineer",
        company: "Fractal",
        location: "Mumbai",
        mode: "Remote",
        experience: "1-3",
        salaryRange: "12–18 LPA",
        skills: ["Python", "TensorFlow", "NLP"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        applyUrl: "https://fractal.ai/careers",
        description: "Build AI models for fortune 500 companies. \nWork on NLP and Computer Vision projects. \nResearch oriented role."
    },
    {
        id: 26,
        title: "React Developer",
        company: "Cars24",
        location: "Gurgaon",
        mode: "Onsite",
        experience: "1-3",
        salaryRange: "10–15 LPA",
        skills: ["React", "Redux", "Saga"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        applyUrl: "https://www.cars24.com/careers",
        description: "Revamp the car buying experience online. \nCreate responsive and interactive web UIs. \nOptimize for mobile web performance."
    },
    {
        id: 27,
        title: "Golang Developer",
        company: "Juspay",
        location: "Bangalore",
        mode: "Onsite",
        experience: "0-1",
        salaryRange: "12–18 LPA",
        skills: ["Go", "Functional Programming", "Haskell"],
        source: "DeepSource",
        postedDaysAgo: 0,
        applyUrl: "https://juspay.in/careers",
        description: "Processing payments with mathematical correctness. \nWe love functional programming and strong types. \nChallenging engineering culture."
    },
    {
        id: 28,
        title: "PHP Developer",
        company: "TechMahindra",
        location: "Pune",
        mode: "Hybrid",
        experience: "3-5",
        salaryRange: "6–10 LPA",
        skills: ["Laravel", "MySQL", "PHP"],
        source: "Naukri",
        postedDaysAgo: 8,
        applyUrl: "https://careers.techmahindra.com",
        description: "Maintain legacy systems and build new modules. \nWork with Telecom clients. \nGood understanding of MVC framework required."
    },
    {
        id: 29,
        title: "Flutter Developer",
        company: "Dream11",
        location: "Mumbai",
        mode: "Onsite",
        experience: "1-3",
        salaryRange: "15–25 LPA",
        skills: ["Flutter", "Dart", "Firebase"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        applyUrl: "https://jobs.lever.co/dream11",
        description: "Build the world's largest fantasy sports app. \nHandle massive scale during IPL seasons. \nSmooth animations and real-time updates."
    },
    {
        id: 30,
        title: "Intern - Data Science",
        company: "Myntra",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        salaryRange: "₹30k–₹50k/month Internship",
        skills: ["Python", "Pandas", "SQL"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        applyUrl: "https://careers.myntra.com",
        description: "Fashion meets Data Science. \nWork on recommendation engines and trend forecasting. \nGreat place to learn from industry experts."
    },
    {
        id: 31,
        title: "Site Reliability Engineer",
        company: "MakeMyTrip",
        location: "Gurgaon",
        mode: "Hybrid",
        experience: "3-5",
        salaryRange: "16–22 LPA",
        skills: ["Linux", "AWS", "Monitoring"],
        source: "Naukri",
        postedDaysAgo: 5,
        applyUrl: "https://www.makemytrip.com/careers",
        description: "Keep the travel platform running 24/7. \nIncident management and root cause analysis. \nAutomate toil using Python/Go."
    },
    {
        id: 32,
        title: "Frontend Developer",
        company: "Lenskart",
        location: "Delhi",
        mode: "Onsite",
        experience: "1-3",
        salaryRange: "9–14 LPA",
        skills: ["React", "HTML5", "SASS"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        applyUrl: "https://blog.lenskart.com/hiring",
        description: "Revolutionize eyewear retail in India. \nBuild 3D try-on features and smooth catalogs. \nFast shipping features integration."
    },
    {
        id: 33,
        title: "Graphic Designer",
        company: "Nykaa",
        location: "Mumbai",
        mode: "Onsite",
        experience: "0-1",
        salaryRange: "4–6 LPA",
        skills: ["Photoshop", "Illustrator", "Social Media"],
        source: "LinkedIn",
        postedDaysAgo: 6,
        applyUrl: "https://www.nykaa.com/careers",
        description: "Create stunning visuals for beauty products. \nWork with marketing team for campaigns. \nHigh aesthetic sense required."
    },
    {
        id: 34,
        title: "Blockchain Developer",
        company: "Polygon",
        location: "Remote",
        mode: "Remote",
        experience: "1-3",
        salaryRange: "20–40 LPA",
        skills: ["Solidity", "Ethereum", "Web3.js"],
        source: "Web3 Careers",
        postedDaysAgo: 1,
        applyUrl: "https://polygon.technology/careers",
        description: "Build the future of Ethereum scaling. \nWork on protocol level changes or dApps. \nFully remote and global team."
    },
    {
        id: 35,
        title: "Junior Data Scientist",
        company: "MuSigma",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        salaryRange: "5–7 LPA",
        skills: ["R", "Statistics", "Python"],
        source: "Naukri",
        postedDaysAgo: 8,
        applyUrl: "https://www.mu-sigma.com/careers",
        description: "Solve business problems using math and data. \nRigorous training program for new joiners. \nClient facing role."
    },
    {
        id: 36,
        title: "Product Manager",
        company: "Meesho",
        location: "Bangalore",
        mode: "Onsite",
        experience: "3-5",
        salaryRange: "25–35 LPA",
        skills: ["Product Strategy", "Analytics", "SQL"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        applyUrl: "https://meesho.io/careers",
        description: "Empower small businesses across India. \nDefine product roadmap for user growth. \nData driven decision making."
    },
    {
        id: 37,
        title: "Angular Developer",
        company: "Mindtree",
        location: "Bhubaneswar",
        mode: "Hybrid",
        experience: "1-3",
        salaryRange: "5–9 LPA",
        skills: ["Angular", "TypeScript", "RxJS"],
        source: "Naukri",
        postedDaysAgo: 7,
        applyUrl: "https://www.mindtree.com/careers",
        description: "Modernize legacy web applications. \nBuild reusable components and services. \nGood knowledge of state management."
    },
    {
        id: 38,
        title: "Node.js Developer",
        company: "Dunzo",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3",
        salaryRange: "12–18 LPA",
        skills: ["Node.js", "MongoDB", "Redis"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        applyUrl: "https://www.dunzo.com/careers",
        description: "Power quick commerce in Indian cities. \nOptimize delivery algorithms and tracking. \nHigh scale real-time systems."
    },
    {
        id: 39,
        title: "Network Engineer",
        company: "Airtel",
        location: "Gurgaon",
        mode: "Onsite",
        experience: "0-1",
        salaryRange: "4–6 LPA",
        skills: ["CCNA", "Routing", "Switching"],
        source: "Naukri",
        postedDaysAgo: 5,
        applyUrl: "https://www.airtel.in/careers",
        description: "Maintain core network infrastructure. \nMonitor network health and uptime. \nField work may be required."
    },
    {
        id: 40,
        title: "SAP Consultant",
        company: "IBM",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "3-5",
        salaryRange: "10–15 LPA",
        skills: ["SAP HANA", "Cloud", "Migration"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        applyUrl: "https://www.ibm.com/in-en/employment",
        description: "Consult for top tier global clients. \nLead SAP migration projects to cloud. \nDeep technical expertise needed."
    },
    {
        id: 41,
        title: "iOS Developer",
        company: "ShareChat",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        salaryRange: "15–22 LPA",
        skills: ["Swift", "iOS", "Objective-C"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        applyUrl: "https://sharechat.com/careers",
        description: "Build social media features for Bharat. \nFocus on video playback and camera features. \nPerformance optimization for older devices."
    },
    {
        id: 42,
        title: "Game Developer",
        company: "Moonfrog",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        salaryRange: "10–16 LPA",
        skills: ["Unity 3D", "C#", "Game Design"],
        source: "LinkedIn",
        postedDaysAgo: 6,
        applyUrl: "https://moonfroglabs.com/careers",
        description: "Create engaging mobile games like Ludo Club. \nWork on game physics and multiplayer logic. \nPassion for gaming is a must."
    },
    {
        id: 43,
        title: "Embedded Engineer",
        company: "Bosch",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        salaryRange: "6–10 LPA",
        skills: ["C", "Embedded Systems", "Automotive"],
        source: "Naukri",
        postedDaysAgo: 4,
        applyUrl: "https://www.bosch.in/careers",
        description: "Work on next-gen automotive software. \nADAS and infotainment systems. \nStrict coding standards (MISRA C)."
    },
    {
        id: 44,
        title: "Content Writer (Tech)",
        company: "GeeksforGeeks",
        location: "Noida",
        mode: "Hybrid",
        experience: "0-1",
        salaryRange: "3–5 LPA",
        skills: ["Writing", "DSA", "SEO"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        applyUrl: "https://practice.geeksforgeeks.org/careers",
        description: "Write technical articles for developers. \nExplain complex algorithms simply. \nHelp millions of students learn coding."
    },
    {
        id: 45,
        title: "Ruby on Rails Developer",
        company: "Gojek",
        location: "Bangalore",
        mode: "Remote",
        experience: "3-5",
        salaryRange: "20–30 LPA",
        skills: ["Ruby", "Rails", "Postgres"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        applyUrl: "https://www.gojek.io/careers",
        description: "Build the Super App of Southeast Asia. \nWork on ride-hailing and food delivery tech. \nScale systems to millions of requests."
    },
    {
        id: 46,
        title: "UI Engineer",
        company: "Postman",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        salaryRange: "18–26 LPA",
        skills: ["React", "Design Systems", "Canvas"],
        source: "Postman Careers",
        postedDaysAgo: 0,
        applyUrl: "https://www.postman.com/careers",
        description: "Build the API platform for developers. \nWork on complex desktop-like web interactions. \nFocus on accessibility and performance."
    },
    {
        id: 47,
        title: "Intern - Cyber Security",
        company: "Cisco",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        salaryRange: "₹40k/month Internship",
        skills: ["Networking", "Python", "Linux"],
        source: "Cisco Careers",
        postedDaysAgo: 5,
        applyUrl: "https://jobs.cisco.com",
        description: "Secure the networks of the future. \nLearn from the best security experts. \nWork on firewall and VPN products."
    },
    {
        id: 48,
        title: "Marketing Analyst",
        company: "InMobi",
        location: "Bangalore",
        mode: "Onsite",
        experience: "0-1",
        salaryRange: "7–10 LPA",
        skills: ["Excel", "SQL", "AdTech"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        applyUrl: "https://www.inmobi.com/company/careers",
        description: "Analyze ad campaign performance. \nOptimize ROI for advertisers. \nWork with big data sets."
    },
    {
        id: 49,
        title: "Frontend Architect",
        company: "Udaan",
        location: "Bangalore",
        mode: "Office",
        experience: "5+",
        salaryRange: "35–50 LPA",
        skills: ["Architecture", "React", "Performance"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        applyUrl: "https://udaan.com/careers",
        description: "Architect the B2B e-commerce platform. \nSolve problems for next billion users. \nDeep technical leadership role."
    },
    {
        id: 50,
        title: "Support Engineer",
        company: "Freshworks",
        location: "Chennai",
        mode: "Hybrid",
        experience: "0-1",
        salaryRange: "4–6 LPA",
        skills: ["SaaS", "Communication", "Debugging"],
        source: "Freshworks Careers",
        postedDaysAgo: 1,
        applyUrl: "https://www.freshworks.com/company/careers",
        description: "Delight customers with quick resolutions. \nUnderstand SaaS products deeply. \npathway to engineering or product roles."
    },
    {
        id: 51,
        title: "Quant Researcher",
        company: "Tower Research",
        location: "Gurgaon",
        mode: "Onsite",
        experience: "0-1",
        salaryRange: "25–40 LPA",
        skills: ["Math", "C++", "Algorithms"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        applyUrl: "https://www.tower-research.com/careers",
        description: "Build high frequency trading strategies. \nWork with extreme low latency systems. \nTop tier math skills required."
    },
    {
        id: 52,
        title: "HR Intern",
        company: "KPMG",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        salaryRange: "₹15k/month Internship",
        skills: ["Communication", "Excel", "Recruitment"],
        source: "Naukri",
        postedDaysAgo: 6,
        applyUrl: "https://home.kpmg/in/en/home/careers.html",
        description: "Assist in campus recruitment drives. \nManage candidate databases. \nLearn corporate HR policies."
    },
    {
        id: 53,
        title: "Java Developer",
        company: "Goldman Sachs",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        salaryRange: "18–24 LPA",
        skills: ["Java", "Spring", "Kafka"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        applyUrl: "https://www.goldmansachs.com/careers",
        description: "Build financial platforms for global markets. \nWork in a high pressure, high reward environment. \nStrong focus on system resilience."
    },
    {
        id: 54,
        title: "React Developer",
        company: "NoBroker",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        salaryRange: "8–14 LPA",
        skills: ["React", "Redux", "Maps API"],
        source: "Naukri",
        postedDaysAgo: 5,
        applyUrl: "https://www.nobroker.in/careers",
        description: "Change how people rent houses. \nWork on map based search and listings. \nFast paced startup culture."
    },
    {
        id: 55,
        title: "Python Engineer",
        company: "BrowserStack",
        location: "Mumbai",
        mode: "Remote",
        experience: "1-3",
        salaryRange: "14–20 LPA",
        skills: ["Python", "Selenium", "Testing"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        applyUrl: "https://www.browserstack.com/careers",
        description: "Build the infrastructure for testing the web. \nWork with device farms and cloud browsers. \nSolve unique concurrency problems."
    },
    {
        id: 56,
        title: "UX Researcher",
        company: "Swiggy",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        salaryRange: "10–16 LPA",
        skills: ["User Interviews", "Usability Testing"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        applyUrl: "https://careers.swiggy.com",
        description: "Understand the needs of hungry customers. \nConduct field research and usability tests. \nInfluence product direction."
    },
    {
        id: 57,
        title: "Supply Chain Analyst",
        company: "Unilever",
        location: "Mumbai",
        mode: "Onsite",
        experience: "0-1",
        salaryRange: "8–12 LPA",
        skills: ["Supply Chain", "Excel", "SAP"],
        source: "Naukri",
        postedDaysAgo: 7,
        applyUrl: "https://careers.unilever.com",
        description: "Optimize the supply chain for FMCG giant. \nEnsure product availability across India. \nWork with logistics partners."
    },
    {
        id: 58,
        title: "Manual Tester",
        company: "TCS",
        location: "Chennai",
        mode: "Onsite",
        experience: "Fresher",
        salaryRange: "3.5 LPA",
        skills: ["Testing Concepts", "SQL"],
        source: "Naukri",
        postedDaysAgo: 1,
        applyUrl: "https://www.tcs.com/careers",
        description: "Execute test cases for insurance project. \nReport bugs in defect tracking tool. \nShift based work."
    },
    {
        id: 59,
        title: "DevOps Intern",
        company: "Simpl",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        salaryRange: "₹25k/month Internship",
        skills: ["Docker", "Linux", "AWS"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        applyUrl: "https://getsimpl.com/careers",
        description: "Learn how to manage cloud infrastructure. \nAssist senior engineers with deployments. \nWork on monitoring dashboards."
    },
    {
        id: 60,
        title: "Chief Technology Officer",
        company: "Stealth Startup",
        location: "Bangalore",
        mode: "Onsite",
        experience: "5+",
        salaryRange: "Equity + Salary",
        skills: ["Leadership", "Full Stack", "Vision"],
        source: "AngelList",
        postedDaysAgo: 0,
        applyUrl: "https://wellfound.com/jobs",
        description: "Co-found the next big thing in FinTech. \nBuild the MVP from scratch. \nHire and lead the founding engineering team."
    }
];
